name: CI with Environment-Aware Security Gates

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t demo-app:${{ github.ref_name }} .

      - name: Trivy Scan (Dev / Feature)
        if: github.ref_name != 'main'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-app:${{ github.ref_name }}
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Trivy Scan (Production)
        if: github.ref_name == 'main'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-app:${{ github.ref_name }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1
